version: 0.2
environment_variables:
  TEMPLATE_FILES: |
    EnvResources.yml
  CONFIG_FILES: |
    templateconfig_d1.json
phases:
  install:
    commands:
      - echo Build Install
      - printenv
      - npm install
  pre_build:
    commands:
      - echo "Validating CFN templates"
      - >-
        aws cloudformation validate-template --template-body
        file://EnvResources.yml
      - |
        for conf in $CONFIG_FILES; do
          echo "Validating CFN parameters config file $conf"
          jsonlint -q $conf
        done
  build:
    commands:
      - echo "Create and copy cloud formation package"
      - >-
        aws cloudformation package --template EnvResources.yml --s3-bucket
        $S3_BUCKET --output-template template-export.yml
      - echo "Copy template config files"
artifacts:
  type: zip
  files:
    - template-export.yml
    - templateconfig_*.json
